### ISSUE TITLE
Unable to create hex figure

### ISSUE THREAD

**Issue by brunomioto** [luisDVA/hexsession#3]
When I run

```
library(hexsession)
library(dplyr)
snap_tile("test.png")
```
I got this:
![image](https://github.com/user-attachments/assets/9fd064fc-9d5c-47b4-8cc0-62ee7cb203e7)

But the save image is:
![test](https://github.com/user-attachments/assets/c4dd312f-4282-43a8-a992-24eb3a26f7c0)

Just it. Same problem when using `make_tile()`.

Also, when rendering it with `make_tile()`, there is a section for `dplyr` package on html file and `package_data.rds`
![image](https://github.com/user-attachments/assets/07678fe3-97c8-4503-af27-c0c6292339ff)

```
> sessionInfo()
R version 4.3.2 (2023-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default


locale:
[1] LC_COLLATE=Portuguese_Brazil.utf8  LC_CTYPE=Portuguese_Brazil.utf8    LC_MONETARY=Portuguese_Brazil.utf8
[4] LC_NUMERIC=C                       LC_TIME=Portuguese_Brazil.utf8    

time zone: Etc/GMT+3
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_1.1.4           hexsession_0.0.0.9000

loaded via a namespace (and not attached):
 [1] later_1.3.1       utf8_1.2.4        R6_2.5.1          base64enc_0.1-3   fastmap_1.1.1     tidyselect_1.2.1 
 [7] websocket_1.4.1   magrittr_2.0.3    glue_1.6.2        tibble_3.2.1      pkgconfig_2.0.3   generics_0.1.3   
[13] lifecycle_1.0.4   ps_1.7.5          promises_1.2.1    cli_3.6.1         processx_3.8.2    fansi_1.0.6      
[19] chromote_0.3.1    vctrs_0.6.4       compiler_4.3.2    rstudioapi_0.16.0 tools_4.3.2       pillar_1.9.0     
[25] magick_2.8.1      Rcpp_1.0.11       rlang_1.1.2       jsonlite_1.8.8 
```

**Comment by luisDVA** [comment]
Hi!
Thanks for opening this issue. Is a qmd file being created in a new folder in your working directory?

**Comment by brunomioto** [comment]
Thanks!
Yes, here is the file:

```
---
execute:
  echo: false
params:
  temp_file_path: "package_data.rds"
  js_file_path: "hexsession.js"
  dark_mode: false
resources:
  - images
embed-resources: true
---

```{r}
#| echo: false



library(htmltools)

# Include the JavaScript file
htmltools::tagList(
  htmltools::tags$script(src = params$js_file_path)
)
```{just adding it to print it better on github}

```{=html}
<div class="main">
  <div class="container" id="imageContainer">
    <!-- Images will be dynamically added here -->
  </div>
  <div class="attribution">
    created with <a href="https://github.com/luisdva/hexsession" target="_blank">hexsession</a>
  </div>
</div>

<style>
body {
  background-color: var(--bg-color);
  color: var(--text-color);
}

.main {
  position: relative;
  display: flex;
  --s: 100px;  /* size  */
  --m: 2px;    /* margin */
  --f: calc(1.732 * var(--s) + 4 * var(--m) - 1px);
}

.container {
  font-size: 0; /*disable white space between inline block element */
}

.container div {
  width: var(--s);
  margin: var(--m);
  height: calc(var(--s)*1.1547); 
  display: inline-block;
  font-size: initial;
  clip-path: polygon(0% 25%, 0% 75%, 50% 100%, 100% 75%, 100% 25%, 50% 0%);
  background: var(--tile-bg);
  margin-bottom: calc(var(--m) - var(--s)*0.2885); 
  overflow: hidden;
  transition: all 0.3s ease;
}

.container::before {
  content: "";
  width: calc(var(--s)/2 + var(--m));
  float: left;
  height: 120%;
  shape-outside: repeating-linear-gradient(     
                   #0000 0 calc(var(--f) - 3px),      
                   #000  0 var(--f));
}

.container div img {
  width: 100%;
  height: 100%;
  object-fit: cover;
  transition: all 0.3s ease;
}

.container a {
  display: block;
  width: 100%;
  height: 100%;
}

/* Subtle hover effect */
.container div:hover {
  z-index: 1;
  transform: scale(1.05);  /* Reduced scale */
  box-shadow: 0 4px 8px rgba(0,0,0,0.1);  /* Subtle shadow */
}

.container div:hover img {
  filter: brightness(1.1);  /* Slightly brighten the image */
}

.attribution {
  position: absolute;
  bottom: -44px;
  right: 40px;
  font-size: 0.8em;
  color: var(--text-color);
  background-color: var(--attribution-bg);
  padding: 2px 5px;
  border-radius: 3px;
  z-index: 10;
  pointer-events: none;  /* Allows clicking through to underlying elements */
}

.attribution a {
  color: var(--link-color);
  text-decoration: none;
  pointer-events: auto;  /* Re-enables clicking on the link */
}

.attribution a:hover {
  text-decoration: underline;
}
</style>

```

**Comment by luisDVA** [comment]
:thinking: 
I was afraid that the template was not being copied and populated properly, but that does not seem to be the case.
Can you share the output of  running `quarto --version`  in your terminal?

**Comment by brunomioto** [comment]
1.5.57

**Comment by luisDVA** [comment]
thats quite recent so it shouldn't be a rendering issue. Can you see an html file in the folder that was created by `make_tile`?

**Comment by brunomioto** [comment]
No, the rendered version I sent earlier was made from the rendered Quarto file
![image](https://github.com/user-attachments/assets/de399398-d66d-4b12-b017-fa2c317c93c7)

**Comment by luisDVA** [comment]
I hadn't seen the blank html output you posted earlier. So that came from rendering the qmd file manually?
The `make_tile` function calls `quarto render` using parameters so that's why you might not be getting the same output. 

Try deleting the temp_hexsession folder created in your working directory, loading dplyr as you had done before, and running `make_tile`.  There may be some setting in your R environment that doesn't let RStudio run the `system()` command. Hopefully that's not the case because I'm not too familiar with that.

**Comment by brunomioto** [comment]
Now I got it rendered to a html. But it didn't work.
![image](https://github.com/user-attachments/assets/cf9837b6-3eac-4407-ba17-f953ff5fb438)
![image](https://github.com/user-attachments/assets/e5287594-2804-44c8-b6d2-1cfe65ca374e)

**Comment by luisDVA** [comment]
what occurs to me know is to address that warning with htmltools, since it's used to create the js code that inserts the images in the html div

**Comment by luisDVA** [comment]
hi @brunomioto I see now that this is an issue with the not function not working properly for tiling just one logo. Install the latest version and try with two or more packages!

**Comment by brunomioto** [comment]
> hi @brunomioto I see now that this is an issue with the not function not working properly for tiling just one logo. Install the latest version and try with two or more packages!

Everything is working now! Thanks!

**Comment by luisDVA** [comment]
latest commit fixes single-logo tiles. closing
